Adding Node Boost to Config
NinjaMandalorian/TownyProduction pull request #24
Opened 2022-12-31 18:04 UTC by Xavbeat03

Added the Node Boost Boolean to config as well as the getter for the value in TownyProductionSettings.java Name of value may have to be refined.

2022-12-31 18:06 UTC, Xavbeat03 commented
Things that need to be completed:
- [ ] Costs money for the duration of increased production
- [ ] Certain NodeTypes can have a flag "UNBOOSTABLE" that stops /node boost from being executed on them
- [ ] NodeTypes can also have the BOOST-MULT flag that multiplies the cost of boosting
- [ ] Can be disabled in config
- [ ] Testing

2023-01-01 19:02 UTC, NinjaMandalorian requested changes
Good start, I can finish this off if you want? Whatever is easiest.

With UNIX, you only need to store the end value, as it doesn't really matter when it started.

2023-01-01 19:02 UTC, NinjaMandalorian commented on src/me/NinjaMandalorian/TownyProduction/object/ProductionNode.java
> +	private double nodeBoostPercentage = 0;
You only need to have the end date as a variable in ProductionNode, and the boost % will be a config setting.

2023-01-02 03:41 UTC, Xavbeat03 commented
The system that changes the item amounts is working well.
Catch for node already boosting is doing well.
Not sure how to check if PERMs is working, or the node flags, so that'll need to be tested later
Also not sure how to add the checks for money or subtracting it, gonna need to figure that out

2023-01-02 06:24 UTC, Xavbeat03 commented
Flags don't seem to be getting properly @NinjaMandalorian if you have a second, can you take a look and figure out why?

2023-01-02 23:37 UTC, NinjaMandalorian approved these changes
Tested and working.

2023-01-03 04:15 UTC, merged